### ISSUE TITLE
Can't get the Line object of a particular customer

### ISSUE THREAD

**Issue by biswo33** [routablehq/python-quickbooks#252]
invoice = Invoice.filter(CustomerRef='1', qb=client)
print(invoice.Line)

giving error saying invoice don't have any Line item.

**Comment by ej2** [comment]
Could you post the error message and a more complete code sample?

**Comment by biswo33** [comment]
Thanks for your help sir.

**Comment by ej2** [comment]
After you find the invoice or customer you want to delete, call the `delete` function:
```
invoice.delete()
customer.delete()
```
