### ISSUE TITLE
Open ID Flow Update

### ISSUE THREAD

**Issue by cheevera** [routablehq/python-quickbooks#348]
As described in the article below, Intuit plans to update to a new Open ID flow after May 3rd 2024. Is this project up to date with those changes, and if so which is the oldest version supported?

https://blogs.intuit.com/2023/09/05/changes-to-identity-signature-keys-that-may-impact-your-application/

**Comment by anthonyto** [comment]
This project does not implement OpenID Connect anywhere. It uses OAuth 2.0 for authorization and authentication to interact with QuickBooks Online. Of course, your application might use OpenID Connect elsewhere but it would not be from this project.
